#ifndef DTACT_UTIL_H
#define DTACT_UTIL_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace dtact_util {

/*
 Stdio bitmask flag: route the child's stderr through a pipe.
 */
constexpr static const uint32_t DTACT_STDERR_PIPE = 4;

/*
 Stdio bitmask flag: route the child's stdin through a pipe.
 */
constexpr static const uint32_t DTACT_STDIN_PIPE = 1;

/*
 Stdio bitmask flag: route the child's stdout through a pipe.
 */
constexpr static const uint32_t DTACT_STDOUT_PIPE = 2;

/*
 Max concurrent listeners for a single signal kind. Generous for real
 programs (which typically register one listener per signal kind, at
 startup) without the registry needing dynamic growth.
 */
constexpr static const size_t MAX_LISTENERS = 16;

/*
 A spawned child process.

 `wait`/`wait_with_output` consume `self` (ownership transfers into the
 pool closure, so nothing needs to be shared or locked); `kill`/`id`
 are synchronous since they're fast, non-blocking syscalls.
 */
struct DtactChild;

/*
 An open file whose reads/writes are dispatched as real overlapped IOCP
 operations — no thread-pool hop, buffer handed straight to the kernel.
 */
struct DtactFile;

#if defined(DTACT_LINUX)
/*
 An open file whose ops are submitted as real io_uring SQEs.
 */
struct DtactFile;
#endif

#if !defined(DTACT_LINUX)
/*
 An open file whose blocking read/write/metadata operations run on the
 dtact-fs thread pool rather than the calling task's thread.
 */
struct DtactFile;
#endif

/*
 A repeating timer. `tick()` is a plain async method mirroring
 `tokio::time::Interval::tick`.
 */
struct DtactInterval;

/*
 A repeating timer. `tick()` mirrors `tokio::time::Interval::tick`.
 */
struct DtactInterval;

/*
 A stream of a specific signal's deliveries — call `.recv().await`
 repeatedly, once per delivery, mirroring `tokio::signal::unix::Signal`.
 */
struct DtactSignalStream;

/*
 A stream of a specific console-control event's deliveries — call
 `.recv().await` repeatedly, mirroring `tokio::signal::windows`.
 */
struct DtactSignalStream;

/*
 A stream of occurrences of one Unix signal, backed by tokio's
 signal-fd/self-pipe reactor integration instead of dtact-signal's
 own registry. Unlike the native backend, each instance owns its own
 OS-level registration rather than sharing a broadcast registry.
 */
struct DtactSignalStream;

/*
 A stream of occurrences of one Windows console-control event
 (`Ctrl+C` or `Ctrl+Break`), backed by tokio's console-handler
 reactor integration instead of dtact-signal's own registry.
 */
struct DtactSignalStream;

/*
 One end of an in-process duplex pipe. Create a connected pair with
 [`pair`].
 */
struct DtactStream;

/*
 A lock-free, non-blocking TCP listener registered with the dtact-io
 driver. Mirrors the Windows backend's `DtactTcpListener` API so callers
 can switch platforms without code changes.
 */
struct DtactTcpListener;

/*
 An async TCP listener backed by IOCP-issued `AcceptEx`.
 */
struct DtactTcpListener;

/*
 Tokio-backed TCP listener. Mirrors the native backend's
 `DtactTcpListener` API surface.
 */
struct DtactTcpListener;

/*
 A lock-free, non-blocking TCP stream registered with the dtact-io
 driver. Mirrors the Windows backend's `DtactTcpStream` API so callers
 can switch platforms without code changes.
 */
struct DtactTcpStream;

/*
 An async TCP stream backed by IOCP-issued `WSARecv`/`WSASend`.
 */
struct DtactTcpStream;

/*
 Tokio-backed TCP stream. Mirrors the native backend's `DtactTcpStream`
 API surface, but drives readiness through tokio's reactor instead of the
 crate's own `IOCP`/`io_uring`/kqueue driver.
 */
struct DtactTcpStream;

/*
 Async UDP socket driven by the native backend (io_uring `SendMsg`/`RecvMsg`
 on Linux, `sendmsg`/`recvmsg` via the mio/kqueue reactor elsewhere).

 Supports the connectionless (`send_to`/`recv_from`) and connected
 (`connect`/`send`/`recv`) patterns, mirroring `std::net::UdpSocket`'s and
 `tokio::net::UdpSocket`'s API shape. The connected `send`/`recv` reuse the
 same `Write`/`Read` submission machinery as [`DtactTcpStream`].
 */
struct DtactUdpSocket;

/*
 Async UDP socket driven by the IOCP backend.

 Supports the connectionless (`send_to`/`recv_from`) and connected
 (`connect`/`send`/`recv`) patterns, mirroring `std::net::UdpSocket`'s and
 `tokio::net::UdpSocket`'s API shape. `send_to`/`recv_from` issue overlapped
 `WSASendTo`/`WSARecvFrom` ops; the connected `send`/`recv` reuse the same
 `WSASend`/`WSARecv` machinery as [`DtactTcpStream`].
 */
struct DtactUdpSocket;

/*
 Async UDP socket — tokio-backend equivalent of the native
 `DtactUdpSocket`, a thin wrapper over [`tokio::net::UdpSocket`].

 Mirrors the connectionless (`send_to`/`recv_from`) and connected
 (`connect`/`send`/`recv`) halves of `std::net::UdpSocket`'s and
 `tokio::net::UdpSocket`'s API so call-sites port across backends with a
 single feature flag.
 */
struct DtactUdpSocket;

extern "C" {

/*
 Close and free a file handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `file` must have
 come from a `dtact_util_fs_file_*` constructor and must not be used
 afterwards.
 */
 void dtact_util_fs_file_close(DtactFile *aFile) ;

/*
 Create (truncating) the file at `path`, returning an owning handle or
 null on error. Free with [`dtact_util_fs_file_close`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `path` must be a
 valid NUL-terminated C string.
 */
 DtactFile *dtact_util_fs_file_create(const char *aPath) ;

/*
 Open the existing file at `path` for reading, returning an owning handle
 or null on error. Free with [`dtact_util_fs_file_close`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `path` must be a
 valid NUL-terminated C string.
 */
 DtactFile *dtact_util_fs_file_open(const char *aPath) ;

/*
 Read up to `len` bytes from `file` (advancing its cursor) into `buf`.
 Returns the byte count read (0 = EOF) or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_fs_file_read(DtactFile *aFile, uint8_t *aBuf, size_t aLen) ;

/*
 Flush `file`'s buffers to disk (`FlushFileBuffers`/`fsync`). Returns 0 on
 success, -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 int32_t dtact_util_fs_file_sync(DtactFile *aFile) ;

/*
 Write `len` bytes from `buf` to `file` (advancing its cursor). Returns
 the byte count written or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_fs_file_write(DtactFile *aFile, const uint8_t *aBuf, size_t aLen) ;

/*
 Initialize the fs backend with `workers` worker threads. Idempotent.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 void dtact_util_fs_init(size_t aWorkers) ;

/*
 Initialize the TCP runtime with `workers` I/O worker threads. Idempotent;
 the first call wins.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 void dtact_util_io_init(size_t aWorkers) ;

/*
 Block until a client connects, returning an owning stream handle (free
 with [`dtact_util_io_stream_close`]) or null on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `listener` must be a
 live handle from [`dtact_util_io_listener_bind`].
 */
 DtactTcpStream *dtact_util_io_listener_accept(DtactTcpListener *aListener) ;

/*
 Bind a TCP listener to `addr` (e.g. `"127.0.0.1:8080"`). Returns an
 owning handle or null on error. Free with
 [`dtact_util_io_listener_close`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `addr` must be a
 valid NUL-terminated C string.
 */
 DtactTcpListener *dtact_util_io_listener_bind(const char *aAddr) ;

/*
 Close and free a listener handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_io_listener_close(DtactTcpListener *aListener) ;

/*
 Close and free a TCP stream handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_io_stream_close(DtactTcpStream *aStream) ;

/*
 Connect to `addr`, blocking until connected. Returns an owning stream
 handle or null on error. Free with [`dtact_util_io_stream_close`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `addr` must be a
 valid NUL-terminated C string.
 */
 DtactTcpStream *dtact_util_io_stream_connect(const char *aAddr) ;

/*
 Read up to `len` bytes from `stream` into `buf`. Returns the byte count
 read (0 = orderly shutdown by peer) or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_io_stream_read(DtactTcpStream *aStream, uint8_t *aBuf, size_t aLen) ;

/*
 Write up to `len` bytes from `buf` to `stream`. Returns the byte count
 written or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_io_stream_write(DtactTcpStream *aStream, const uint8_t *aBuf, size_t aLen) ;

/*
 Bind a UDP socket to `addr` (e.g. `"127.0.0.1:8080"`, or `"0.0.0.0:0"`
 for an ephemeral port). Returns an owning handle or null on error. Free
 with [`dtact_util_io_udp_close`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `addr` must be a
 valid NUL-terminated C string.
 */
 DtactUdpSocket *dtact_util_io_udp_bind(const char *aAddr) ;

/*
 Close and free a UDP socket handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_io_udp_close(DtactUdpSocket *aSock) ;

/*
 Connect `sock` to `addr` so [`dtact_util_io_udp_send`]/
 [`dtact_util_io_udp_recv`] can omit the peer address. Returns 0 on
 success, -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `addr` must be a
 valid NUL-terminated C string.
 */
 int32_t dtact_util_io_udp_connect(DtactUdpSocket *aSock, const char *aAddr) ;

/*
 Receive a datagram from the connected peer into `buf`. Returns the byte
 count received, or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_io_udp_recv(DtactUdpSocket *aSock, uint8_t *aBuf, size_t aLen) ;

/*
 Receive a single datagram into `buf` (capacity `len`).

 On success writes the sender's `"host:port"` address as a
 NUL-terminated string into `out_addr` (capacity `out_addr_cap`,
 truncated if it doesn't fit) and returns the byte count received;
 returns -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `out_addr`, if
 non-null, must point to at least `out_addr_cap` writable bytes.
 */

ptrdiff_t dtact_util_io_udp_recv_from(DtactUdpSocket *aSock,
                                      uint8_t *aBuf,
                                      size_t aLen,
                                      char *aOutAddr,
                                      size_t aOutAddrCap)
;

/*
 Send `len` bytes from `buf` to the connected peer (see
 [`dtact_util_io_udp_connect`]). Returns the byte count sent, or -1 on
 error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_io_udp_send(DtactUdpSocket *aSock, const uint8_t *aBuf, size_t aLen) ;

/*
 Send `len` bytes from `buf` as a single datagram to `target` (a
 NUL-terminated `"host:port"` string). Returns the byte count sent, or -1
 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `target` must be a
 valid NUL-terminated C string.
 */

ptrdiff_t dtact_util_io_udp_send_to(DtactUdpSocket *aSock,
                                    const uint8_t *aBuf,
                                    size_t aLen,
                                    const char *aTarget)
;

/*
 Return the current thread's last-error message as a NUL-terminated C
 string, or null if no error has been recorded since the last successful
 call.

 The returned pointer is owned by the library and remains valid only
 until the next `dtact-util` FFI call on this thread. Do not free it.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. This function reads
 only thread-local state and takes no pointer arguments.
 */
 const char *dtact_util_last_error_message() ;

/*
 Free a child handle without waiting (leaves a zombie on Unix if the
 child hasn't been reaped). Prefer [`dtact_util_process_child_wait`].
 Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_process_child_free(DtactChild *aChild) ;

/*
 Return the child's OS process id, or 0 if `child` is null.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 uint32_t dtact_util_process_child_id(DtactChild *aChild) ;

/*
 Kill the child (does not reap it — still call
 [`dtact_util_process_child_wait`] or [`dtact_util_process_child_free`]).
 Returns 0 on success, -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 int32_t dtact_util_process_child_kill(DtactChild *aChild) ;

/*
 Take ownership of the child's stderr pipe (only if spawned with
 [`DTACT_STDERR_PIPE`]). Returns null if unavailable or already taken.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 DtactChildStderr *dtact_util_process_child_take_stderr(DtactChild *aChild) ;

/*
 Take ownership of the child's stdin pipe (only if spawned with
 [`DTACT_STDIN_PIPE`]). Returns null if unavailable or already taken.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 DtactChildStdin *dtact_util_process_child_take_stdin(DtactChild *aChild) ;

/*
 Take ownership of the child's stdout pipe (only if spawned with
 [`DTACT_STDOUT_PIPE`]). Returns null if unavailable or already taken.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 DtactChildStdout *dtact_util_process_child_take_stdout(DtactChild *aChild) ;

/*
 Block until the child exits, writing its exit code into `*out_code`.

 **Consumes and frees `child`** — do not use the handle afterwards.
 Returns 0 on success, -1 on error (e.g. the platform reported no exit
 code, as for a signal-terminated process on Unix).

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `child` must be a
 live handle; `out_code`, if non-null, must be writable.
 */
 int32_t dtact_util_process_child_wait(DtactChild *aChild, int32_t *aOutCode) ;

/*
 Initialize the process backend's blocking-op pool with `workers`
 threads. Idempotent (the pool also self-initializes on first use).

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 void dtact_util_process_init(size_t aWorkers) ;

/*
 Spawn `program` as a child process.

 Takes `arg_count` arguments (`argv[0..arg_count]`, none of which is the
 program name) and the given `stdio_flags` (see [`DTACT_STDIN_PIPE`]
 etc.). Returns an owning child handle or null on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `program` must be a
 valid C string; `argv` must be non-null when `arg_count > 0` and point to
 `arg_count` valid C-string pointers.
 */

DtactChild *dtact_util_process_spawn(const char *aProgram,
                                     const char *const *aArgv,
                                     size_t aArgCount,
                                     uint32_t aStdioFlags)
;

/*
 Free the child's stderr pipe handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_process_stderr_free(DtactChildStderr *aStderr) ;

/*
 Read up to `len` bytes from the child's stderr into `buf`. Returns the
 byte count read (0 = EOF) or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_process_stderr_read(DtactChildStderr *aStderr, uint8_t *aBuf, size_t aLen) ;

/*
 Close (free) the child's stdin pipe, letting the child observe EOF.
 Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_process_stdin_close(DtactChildStdin *aStdin) ;

/*
 Write `len` bytes from `buf` to the child's stdin. Returns the byte count
 written or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */

ptrdiff_t dtact_util_process_stdin_write(DtactChildStdin *aStdin,
                                         const uint8_t *aBuf,
                                         size_t aLen)
;

/*
 Free the child's stdout pipe handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_process_stdout_free(DtactChildStdout *aStdout) ;

/*
 Read up to `len` bytes from the child's stdout into `buf`. Returns the
 byte count read (0 = EOF) or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_process_stdout_read(DtactChildStdout *aStdout, uint8_t *aBuf, size_t aLen) ;

/*
 Register a listener for Ctrl+Break (`CTRL_BREAK_EVENT`), returning an
 owning handle. Free with [`dtact_util_signal_free`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 DtactSignalStream *dtact_util_signal_ctrl_break() ;

/*
 Register a listener for Ctrl+C (`CTRL_C_EVENT`), returning an owning
 handle. Free with [`dtact_util_signal_free`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 DtactSignalStream *dtact_util_signal_ctrl_c() ;

/*
 Free a signal listener handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_signal_free(DtactSignalStream *aStream) ;

/*
 Block until this signal is next delivered.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `stream` must be a
 live handle from one of the signal constructors above.
 */
 void dtact_util_signal_recv(DtactSignalStream *aStream) ;

/*
 Register a listener for a raw signal number (`libc::SIGINT` etc.),
 returning an owning handle. Free with [`dtact_util_signal_free`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 DtactSignalStream *dtact_util_signal_register(int aSignum) ;

/*
 Free (close) a stream endpoint. Dropping it lets the peer observe EOF on
 its next read. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 void dtact_util_stream_free(DtactStream *aStream) ;

/*
 Create a connected pair of duplex streams.

 Each side buffers `capacity` bytes per direction (rounded up to a power
 of two). On success writes two owning handles into `out_a` / `out_b` and
 returns 0; on error returns -1 and records a message.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `out_a` and `out_b`
 must be non-null, writable, and point to storage for one pointer each.
 */
 int32_t dtact_util_stream_pair_create(size_t aCapacity, DtactStream **aOutA, DtactStream **aOutB) ;

/*
 Read up to `len` bytes from `stream` into `buf`. Returns the number of
 bytes read (0 = EOF, peer's write half dropped), or -1 on error.

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_stream_read(DtactStream *aStream, uint8_t *aBuf, size_t aLen) ;

/*
 Write up to `len` bytes from `buf` into `stream`. Returns the number of
 bytes written, or -1 on error (e.g. the peer dropped its read half).

 # Safety

 See the [`crate::ffi`] module-level Safety contract.
 */
 ptrdiff_t dtact_util_stream_write(DtactStream *aStream, const uint8_t *aBuf, size_t aLen) ;

/*
 Create a repeating interval timer with the given period in milliseconds.

 Returns an owning handle, or null if `period_millis` is 0 (an error is
 recorded). Free with [`dtact_util_timer_interval_free`].

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 DtactInterval *dtact_util_timer_interval_create(uint64_t aPeriodMillis) ;

/*
 Free an interval handle. Passing null is a no-op.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `interval` must have
 come from [`dtact_util_timer_interval_create`] and must not be used
 afterwards.
 */
 void dtact_util_timer_interval_free(DtactInterval *aInterval) ;

/*
 Block until this interval's next tick fires.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. `interval` must be a
 live handle from [`dtact_util_timer_interval_create`].
 */
 void dtact_util_timer_interval_tick(DtactInterval *aInterval) ;

/*
 Block the calling thread for `millis` milliseconds using the native
 timer wheel.

 # Safety

 See the [`crate::ffi`] module-level Safety contract. Takes no pointers.
 */
 void dtact_util_timer_sleep_ms(uint64_t aMillis) ;

}  // extern "C"

}  // namespace dtact_util

#endif  // DTACT_UTIL_H
